### ISSUE TITLE
Clarify use cases in README

### ISSUE THREAD

**Issue by vvkh** [avito-tech/aqueduct#2]
Current intro in README seems a bit misleading
> Framework for creating efficient data processing pipelines.

As "data pipelines" already have strong association with some kind of ETL processes and frameworks like luigi, airflow, pyspark, etc.

I suggest getting rid of "data pipelines" term in README and adding explicit use cases somewhere in the beginning of the docs.

**Comment by bugrimov** [comment]
Thanks, we also sees this problem. We think how to rename data pipelines without loosing meaning. Maybe 'production pipeline' will be better.

**Comment by bugrimov** [comment]
Changed description to 'Framework for performance-efficient prediction'
